### ISSUE TITLE
Appears to be broken for 17.0.0+ versions

### ISSUE THREAD

**Issue by marcoRS** [Commit451/Notifire#2]
The library currently breaks for any `firebase-messaging` versions greater than 17.0.0+ because it depends on a private `Bundle` variable within the `RemoteMessage` class. 

I can see from the source code the need to get the `Bundle` to check for some channel info however this can be done without hardcoding the name by using the `toIntent()` function in `RemoteMessage` class. 

```kotlin
fun RemoteMessage.toNotificationBuilder(context: Context, defaultTitle: String, @DrawableRes defaultNotificationResource: Int): NotificationCompat.Builder {
   .... initial code
    // val bundle = Util.getBundle(this)
        val bundle = toIntent().extras
   ....  rest of code
}
```

Can we update this to use that function instead and update the dependency on `firebase-messaging` to `18.0.0` ? 

I can submit a PR if required.

**Comment by Jawnnypoo** [comment]
Thanks for notifying me, fixed in 1.5.0 🎉
